version: '3'
services:
  zk1:
    image: confluentinc/cp-zookeeper:4.1.0
    logging:
        options:
          max-size: "10m"
          max-file: "20"    
    networks:
        - kafka-net
    restart: always    
    environment:
        ZOO_MY_ID: 1
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOO_SERVERS: server.1=16.168.0.2:2888:3888
        KAFKA_JMX_HOSTNAME: 16.168.0.2
    volumes:
        - ./zookeeperdata/data:/var/lib/zookeeper/data
        - ./zookeeperdata/log:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "20"
    environment:   
        KAFKA_LISTENERS: PLAINTEXT://:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://16.168.0.3:9092
        KAFKA_ZOOKEEPER_CONNECT: zk1:2181
        KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        KAFKA_NUM_PARTITIONS: 100
        KAFKA_COMPRESSION_TYPE: 'lz4'
        KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'false'
        KAFKA_LOG_CLEANER_ENABLE: 'true'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1      
        KAFKA_MAX_CONNECTIONS_PER_IP: 1000
        KAFKA_DELETE_TOPIC_ENABLE: 'true'
        KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,state.change.logger=INFO"
        KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO
    volumes:
        - ./data:/var/lib/kafka/data
    networks:
        - kafka-net
    ports:
        - 9092:9092
    depends_on:
      - zk1    
    restart: always

networks:
    kafka-net:
        external:
            name: kafka_net
