version: '3'
services:
 cassandra-node1:
   image: cassandra:latest
   environment:
     - CASSANDRA_CLUSTER_NAME=cassandra-cluster
     - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
     - CASSANDRA_PASSWORD_SEEDER=yes
     - CASSANDRA_PASSWORD=password123
   ports:
     - 9042:9042
     - 7199:7199

 cassandra-node2:
   image: cassandra:latest
   environment:
     - CASSANDRA_CLUSTER_NAME=cassandra-cluster
     - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
     - CASSANDRA_PASSWORD=password123
   ports:
     - 9043:9042
     - 7200:7199
